export const SET_LOGIN: string = 'SET_LOGIN'
export const FETCH_LOGIN: string = 'FETCH_LOGIN'
export const FETCH_REGIN: string = 'FETCH_REGIN'
export const LOGOUT: string = 'LOGOUT'
export const ENTER: string = 'ENTER'